# Generated by Django 6.1 on 2026-08-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_creer_groupes_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='specialite',
            field=models.CharField(blank=True, choices=[('generale', 'Médecine générale'), ('cardiologie', 'Cardiologie'), ('dermatologie', 'Dermatologie'), ('endocrinologie', 'Endocrinologie'), ('gastroenterologie', 'Gastro-entérologie'), ('gynecologie', 'Gynécologie-obstétrique'), ('hematologie', 'Hématologie'), ('neurologie', 'Neurologie'), ('oncologie', 'Oncologie'), ('ophtalmologie', 'Ophtalmologie'), ('orl', 'ORL'), ('pediatrie', 'Pédiatrie'), ('pneumologie', 'Pneumologie'), ('psychiatrie', 'Psychiatrie'), ('rhumatologie', 'Rhumatologie'), ('urologie', 'Urologie'), ('autre', 'Autre')], help_text='Spécialité du médecin, le cas échéant.', max_length=30),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='specialite_autre',
            field=models.CharField(blank=True, help_text="Texte libre si specialite='autre'.", max_length=100),
        ),
    ]
