# Generated by Django 6.1 on 2026-08-28 06:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicaments', '0001_initial'),
        ('patients', '0003_alter_patient_options'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite_initiale', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantite_restante', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('delai_reappro_jours', models.PositiveSmallIntegerField(blank=True, help_text='Délai habituel pour obtenir une nouvelle boîte.', null=True)),
                ('seuil_alerte_quantite', models.DecimalField(blank=True, decimal_places=2, help_text='Alerte si quantite_restante passe à ou sous ce seuil.', max_digits=8, null=True)),
                ('seuil_alerte_jours', models.PositiveSmallIntegerField(blank=True, help_text="Alerte si le stock restant (toutes boîtes actives de ce médicament) est estimé à ce nombre de jours ou moins, d'après la consommation réelle récente.", null=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('epuisee', 'Épuisée'), ('perimee', 'Périmée')], default='active', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boites', to='medicaments.medicament')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boites', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Boîte',
                'verbose_name_plural': 'Boîtes',
                'ordering': ['date_peremption'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=8)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('boite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.boite')),
                ('prise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='prescriptions.prise')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_creation'],
            },
        ),
    ]
