# Generated by Django 6.1 on 2026-08-27 05:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_cis', models.CharField(help_text='Code Identifiant de Spécialité officiel (BDPM).', max_length=20, unique=True)),
                ('denomination', models.CharField(max_length=255)),
                ('forme_pharmaceutique', models.CharField(blank=True, max_length=150)),
                ('dosage', models.CharField(blank=True, max_length=150)),
                ('laboratoire', models.CharField(blank=True, max_length=255)),
                ('code_atc', models.CharField(blank=True, help_text='Classification anatomique, thérapeutique et chimique — utile pour le futur module de vérification des interactions.', max_length=10)),
                ('source', models.CharField(default='BDPM', editable=False, max_length=20)),
                ('date_import', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['denomination'],
            },
        ),
    ]
