# Generated by Django 6.1 on 2026-08-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='dosage',
            field=models.CharField(blank=True, help_text='Concaténation de toutes les substances actives (SA) et leur dosage — peut être long pour les médicaments combinant plusieurs substances.', max_length=500),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='forme_pharmaceutique',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
