# Generated by Django 6.1 on 2026-08-28 15:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0002_alter_medicament_dosage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstanceActive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Nom normalisé en MAJUSCULES.', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Substance active',
                'verbose_name_plural': 'Substances actives',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='medicament',
            name='substances_actives',
            field=models.ManyToManyField(blank=True, help_text='Renseigné par import_bdpm --fichier-composition. Utilisé par apps.interactions pour croiser avec le Thésaurus ANSM.', related_name='medicaments', to='medicaments.substanceactive'),
        ),
    ]
