# Generated by Django 6.1 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0003_substanceactive_medicament_substances_actives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='source',
            field=models.CharField(
                choices=[('BDPM', 'BDPM (France)'), ('SWISSMEDIC', 'Swissmedic (Suisse)')],
                default='BDPM',
                editable=False,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='medicament',
            name='verification_interactions_fiable',
            field=models.BooleanField(
                default=True,
                help_text="False si les substances actives n'ont pas pu être rapprochées avec "
                "certitude des noms utilisés par le Thésaurus des interactions (ex. import "
                "Swissmedic : noms de substances en latin, jamais rapprochés automatiquement "
                "des noms français de la BDPM — risque de faux rapprochement trop élevé). "
                "apps.interactions doit avertir l'utilisateur plutôt que de laisser croire à "
                "une vérification faite quand ce champ est False.",
            ),
        ),
    ]
