# Generated by Django 6.1 on 2026-08-28 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescriptions', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('in_app', "Dans l'application")], max_length=10)),
                ('categorie', models.CharField(choices=[('rappel_prise', 'Rappel de prise'), ('alerte_stock', 'Alerte de stock'), ('autre', 'Autre')], max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoyee', 'Envoyée'), ('echec', 'Échec'), ('lue', 'Lue')], default='en_attente', max_length=20)),
                ('erreur', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('boite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='stock.boite')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('prise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='prescriptions.prise')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
