# Generated by Django 6.1 on 2026-09-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=False, help_text="Active l'envoi SMTP réel avec ces réglages. Décoché : les e-mails suivent la configuration du fichier .env (console par défaut).")),
                ('hote', models.CharField(blank=True, max_length=255, verbose_name='Hôte SMTP')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='Port')),
                ('identifiant', models.CharField(blank=True, max_length=255, verbose_name='Identifiant')),
                ('mot_de_passe', models.CharField(blank=True, max_length=255, verbose_name='Mot de passe / clé API')),
                ('utiliser_tls', models.BooleanField(default=True, verbose_name='Utiliser TLS')),
                ('utiliser_ssl', models.BooleanField(default=False, verbose_name='Utiliser SSL')),
                ('adresse_expediteur', models.CharField(blank=True, help_text='Laisser vide pour utiliser DEFAULT_FROM_EMAIL du .env.', max_length=255, verbose_name="Adresse d'expédition")),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration e-mail',
                'verbose_name_plural': 'Configuration e-mail',
            },
        ),
    ]
