# Generated by Django 6.1 on 2026-08-27 05:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteMedicale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categorie', models.CharField(choices=[('allergie', 'Allergie'), ('antecedent', 'Antécédent médical'), ('observation', 'Observation générale')], max_length=20)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Note médicale',
                'verbose_name_plural': 'Notes médicales',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_dossier', models.CharField(max_length=32, unique=True)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin'), ('A', 'Autre / non précisé')], max_length=1)),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=150)),
                ('contact_urgence_telephone', models.CharField(blank=True, max_length=20)),
                ('contact_urgence_lien', models.CharField(blank=True, help_text='Ex. : conjoint, enfant, aidant...', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='PatientMedecin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actif', models.BooleanField(default=True)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Suivi médecin-patient',
                'verbose_name_plural': 'Suivis médecin-patient',
            },
        ),
    ]
