# Generated by Django 6.1 on 2026-08-27 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notemedicale',
            name='saisi_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='utilisateur',
            field=models.OneToOneField(help_text='Compte utilisateur associé (obligatoire).', on_delete=django.db.models.deletion.CASCADE, related_name='fiche_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notemedicale',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_medicales', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientmedecin',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_suivis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientmedecin',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecins_suivi', to='patients.patient'),
        ),
        migrations.AddConstraint(
            model_name='patientmedecin',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('patient', 'medecin'), name='un_seul_suivi_actif_par_couple_patient_medecin'),
        ),
    ]
