# Generated by Django 6.1 on 2026-08-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['numero_dossier'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
    ]
