# Generated by Django 6.1 on 2026-09-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='preference_alerte_stock',
            field=models.CharField(choices=[('patient', 'Patient uniquement'), ('medecin', 'Médecin suiveur uniquement'), ('les_deux', 'Patient et médecin suiveur')], default='patient', help_text='Qui reçoit les alertes de stock (quantité basse, jours restants bas, rupture).', max_length=10),
        ),
    ]
