# Generated by Django 6.1 on 2026-08-28 15:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionNonImportee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protagoniste_a', models.CharField(max_length=255)),
                ('protagoniste_b', models.CharField(max_length=255)),
                ('texte_brut', models.TextField()),
                ('raison_exclusion', models.CharField(max_length=255)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Interaction non importée (à revoir manuellement)',
                'verbose_name_plural': 'Interactions non importées (à revoir manuellement)',
            },
        ),
        migrations.CreateModel(
            name='InteractionMedicamenteuse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protagoniste_a', models.CharField(db_index=True, max_length=255)),
                ('protagoniste_b', models.CharField(db_index=True, max_length=255)),
                ('niveau', models.CharField(choices=[('contre_indication', 'Contre-indication'), ('association_deconseillee', 'Association déconseillée'), ('precaution_emploi', "Précaution d'emploi"), ('a_prendre_en_compte', 'À prendre en compte')], max_length=30)),
                ('libelle', models.TextField(help_text="Texte explicatif complet tel qu'issu du Thésaurus.")),
                ('source', models.CharField(default='Thésaurus ANSM', editable=False, max_length=100)),
                ('date_publication_source', models.DateField(default='2023-09-15')),
                ('date_import', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Interaction médicamenteuse',
                'verbose_name_plural': 'Interactions médicamenteuses',
                'constraints': [models.UniqueConstraint(fields=('protagoniste_a', 'protagoniste_b'), name='paire_protagonistes_unique')],
            },
        ),
    ]
