# Generated by Django 6.1 on 2026-08-28 05:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicaments', '0001_initial'),
        ('patients', '0003_alter_patient_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_prise', models.CharField(choices=[('reguliere', 'Régulière (horaires fixes)'), ('reserve', 'Réserve (usage ponctuel)')], max_length=20)),
                ('dose_quantite', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dose_unite', models.CharField(help_text='Ex. : comprimé, ml, mg', max_length=30)),
                ('frequence_par_jour', models.PositiveSmallIntegerField(blank=True, help_text='Nombre de prises par jour (prescriptions régulières).', null=True)),
                ('dose_max_par_jour', models.DecimalField(blank=True, decimal_places=2, help_text="Plafond journalier pour une prescription 'réserve' (déclenche une alerte si dépassé).", max_digits=6, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, help_text='Vide = traitement en cours.', null=True)),
                ('instructions', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('arretee', 'Arrêtée'), ('terminee', 'Terminée')], default='active', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('medecin_prescripteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_redigees', to=settings.AUTH_USER_MODEL)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='medicaments.medicament')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='HoraireProgramme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heure', models.TimeField()),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actif', models.BooleanField(default=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Horaire programmé',
                'verbose_name_plural': 'Horaires programmés',
                'ordering': ['heure'],
            },
        ),
        migrations.CreateModel(
            name='Prise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_heure_prevue', models.DateTimeField(blank=True, null=True)),
                ('date_heure_reelle', models.DateTimeField(blank=True, null=True)),
                ('quantite_prevue', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quantite_prise', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('statut', models.CharField(choices=[('attendue', 'Attendue'), ('prise', 'Prise'), ('oubliee', 'Oubliée'), ('reportee', 'Reportée')], default='attendue', max_length=20)),
                ('alerte_depassement', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prises_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('horaire_programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prises', to='prescriptions.horaireprogramme')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prises', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Prise',
                'verbose_name_plural': 'Prises',
                'ordering': ['-date_heure_prevue', '-date_heure_reelle'],
            },
        ),
    ]
