# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='confirmation_automatique',
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Prescriptions régulières uniquement. Si activé (par défaut), chaque prise "
                    "programmée (générée à l'avance par generer_prises_attendues) est automatiquement "
                    "marquée 'prise' dès que son heure prévue est atteinte, sans confirmation manuelle "
                    "(voir la commande confirmer_prises_automatiques). Si désactivé, elle reste "
                    "'attendue' jusqu'à une action manuelle du patient/médecin — elle n'est jamais "
                    "basculée automatiquement en 'oubliée'."
                ),
            ),
        ),
    ]
